import { marked } from 'marked'
import hljs from 'highlight.js/lib/core'
import DOMPurify from 'dompurify'

import { latexToPlainText } from './mathPlaintext'
import { CITATION_MARKER, webSource, type Citation } from './citations'

// Register only common languages — the full highlight.js bundle is ~1 MB.
import bash from 'highlight.js/lib/languages/bash'
import c from 'highlight.js/lib/languages/c'
import cpp from 'highlight.js/lib/languages/cpp'
import css from 'highlight.js/lib/languages/css'
import go from 'highlight.js/lib/languages/go'
import java from 'highlight.js/lib/languages/java'
import javascript from 'highlight.js/lib/languages/javascript'
import json from 'highlight.js/lib/languages/json'
import markdown from 'highlight.js/lib/languages/markdown'
import python from 'highlight.js/lib/languages/python'
import rust from 'highlight.js/lib/languages/rust'
import sql from 'highlight.js/lib/languages/sql'
import typescript from 'highlight.js/lib/languages/typescript'
import xml from 'highlight.js/lib/languages/xml'
import yaml from 'highlight.js/lib/languages/yaml'

hljs.registerLanguage('bash', bash)
hljs.registerLanguage('c', c)
hljs.registerLanguage('cpp', cpp)
hljs.registerLanguage('css', css)
hljs.registerLanguage('go', go)
hljs.registerLanguage('java', java)
hljs.registerLanguage('javascript', javascript)
hljs.registerLanguage('json', json)
hljs.registerLanguage('markdown', markdown)
hljs.registerLanguage('python', python)
hljs.registerLanguage('rust', rust)
hljs.registerLanguage('sql', sql)
hljs.registerLanguage('typescript', typescript)
hljs.registerLanguage('xml', xml)
hljs.registerLanguage('yaml', yaml)

/**
 * Markdown → sanitized HTML for assistant messages. Code blocks are
 * syntax-highlighted and wrapped with a header row (language label + Copy
 * button); the copy click is delegated in MessageBubble.
 */

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

marked.use({
  breaks: true,
  gfm: true,
  renderer: {
    code(code: string, infostring: string | undefined): string {
      const requested = (infostring ?? '').trim().split(/\s+/)[0]
      const language = requested && hljs.getLanguage(requested) ? requested : 'plaintext'
      let highlighted: string
      try {
        highlighted = hljs.highlight(code, { language }).value
      } catch {
        highlighted = escapeHtml(code)
      }
      return (
        `<div class="code-block">` +
        `<div class="code-header"><span>${escapeHtml(language)}</span>` +
        `<button type="button" class="code-copy-btn">Copy</button></div>` +
        `<pre><code class="hljs language-${escapeHtml(language)}">${highlighted}</code></pre>` +
        `</div>`
      )
    }
  }
})

/**
 * Beyond DOMPurify's defaults (which already drop scripts, event handlers and
 * javascript: URLs), a chat bubble has no business containing form controls or
 * inline styles: a model — or a web page a tool quoted — could otherwise
 * render a convincing "enter your password" box, or a fixed-position overlay
 * covering the real UI. `button` stays allowed because the code-block header's
 * Copy button is generated by this very renderer. Pinned by test/markdownCheck.ts.
 */
const SANITIZE_OPTIONS = {
  FORBID_TAGS: ['form', 'input', 'textarea', 'select', 'option', 'style'],
  FORBID_ATTR: ['style']
}

export function renderMarkdown(markdown: string, citations: Citation[] = []): string {
  // Models often wrap numbers and units in TeX ($374^\circ\text{C}$); the
  // renderer has no math engine, so rewrite it to plain text first.
  const html = marked.parse(latexToPlainText(markdown), { async: false }) as string
  return DOMPurify.sanitize(linkCitations(stripSandboxImages(html), citations), SANITIZE_OPTIONS)
}

/**
 * v1.13: `[1]` in a reply becomes the passage it names.
 *
 * The library already hands the model numbered passages carrying their
 * document's source URL, and the model already cites them by number — the
 * marker just resolved to nothing on screen. Linked here rather than in the
 * markdown source because the number is the app's, not the model's: only a
 * passage the lookup actually returned gets a link, and an invented number is
 * left as plain text for the grounding pass to report.
 *
 * Rewritten before DOMPurify runs, deliberately: the pack manifest is a file
 * on disk like any other input, so its `source` goes through the same one
 * sanitization boundary as model output. Anchors get no `target` — the app
 * strips it — so a click leaves through `will-navigate`, the same route a
 * link the model merely typed already takes (src/main/index.ts).
 */
export function linkCitations(html: string, citations: Citation[]): string {
  if (citations.length === 0) return html
  const byIndex = new Map(citations.map((c) => [c.index, c]))
  // Tags, then code regions, then runs of text: only the last are rewritten,
  // so a `[1]` inside an attribute or a code sample is left alone.
  return html.replace(/<pre[\s\S]*?<\/pre>|<code[\s\S]*?<\/code>|<[^>]+>|[^<]+/g, (chunk) =>
    chunk.startsWith('<')
      ? chunk
      : chunk.replace(CITATION_MARKER, (raw, n: string) => {
          const c = byIndex.get(Number(n))
          if (!c) return raw
          // Re-checked here, not trusted from the caller: this function is the
          // one that writes the href, so it is the one that decides what may
          // become one. A scheme that is not http(s) reaches neither the
          // attribute nor the tooltip.
          const href = webSource(c.href)
          const title = escapeHtml(href ? `${c.label}\n${href}` : c.label)
          return href
            ? `<a class="citation-ref" href="${escapeHtml(href)}" title="${title}">${raw}</a>`
            : `<span class="citation-ref" title="${title}">${raw}</span>`
        })
  )
}

/**
 * v1.12: a model that saved a chart under /work tends to also write
 * ![chart](/work/chart.png) into its answer — and one that FAILED to save it
 * writes the same markdown anyway (measured live: the only python run errored,
 * the reply embedded the image regardless). The sandbox path can never load in
 * the renderer — real charts arrive through the tool result's image gallery —
 * so a broken-image icon is all that ref can ever render. Drop the tag; the
 * gallery shows the chart when it exists.
 */
export function stripSandboxImages(html: string): string {
  return html.replace(/<img\b[^>]*src=["'](?:file:\/\/)?\/work\/[^"']*["'][^>]*>/gi, '')
}

/**
 * Split a still-streaming reply into a stable prefix and a live tail, so the
 * prefix can be parsed once and memoized while only the growing tail is
 * re-parsed per flush. Without the split, a streaming reply re-parsed,
 * re-highlighted and re-sanitized its entire accumulated text on every
 * repaint — O(n²) over the reply, and worst exactly on long code answers.
 *
 * The split lands on a blank line (a block boundary for everything but
 * tables, which contain no blank lines and so fall wholly into the tail) and
 * never inside an open ``` fence — parsing half a fence turns code into
 * prose. While a fence is open the split retreats to the blank line before
 * it, so the live tail is the open code block and nothing more. Rendering
 * prefix and tail separately can differ from a whole-parse in corner cases
 * (reference links defined early and used late); any such imperfection is
 * transient, because the finished message is always parsed whole.
 */
export function splitStreamingMarkdown(markdown: string): [stable: string, live: string] {
  let idx = markdown.lastIndexOf('\n\n')
  while (idx >= 0) {
    const stable = markdown.slice(0, idx + 2)
    const fences = stable.match(/```/g)
    if (!fences || fences.length % 2 === 0) return [stable, markdown.slice(idx + 2)]
    // Boundary sits inside an open fence — retreat to before its opening.
    idx = markdown.lastIndexOf('\n\n', markdown.lastIndexOf('```', idx) - 1)
  }
  return ['', markdown]
}
